# Generated by Django 3.1.12 on 2021-06-23 14:40

from django.db import migrations
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('activities', '0002_activity_astronomical_scientific_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='age',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, limit_choices_to={'group': 'age'}, null=True, related_name='age', to='activities.Category'),
        ),
        migrations.AddField(
            model_name='activity',
            name='keywords',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='activities.Keyword', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='activity',
            name='learning',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Enquiry-based learning model', limit_choices_to={'group': 'learning'}, null=True, related_name='_activity_learning_+', to='activities.Category', verbose_name='type of learning activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='level',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Specify at least one of "Age" and "Level". ', limit_choices_to={'group': 'level'}, null=True, related_name='_activity_level_+', to='activities.Category', verbose_name='Education level'),
        ),
        migrations.AddField(
            model_name='activity',
            name='skills',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, limit_choices_to={'group': 'skills'}, null=True, related_name='_activity_skills_+', to='activities.Category', verbose_name='core skills'),
        ),
    ]
