# Generated by Django 3.1.12 on 2021-06-23 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20210623_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cost',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': 'cost'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.category', verbose_name='Cost per student'),
        ),
        migrations.AddField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': 'group'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activities.category', verbose_name='Group or individual activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': 'location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activities.category'),
        ),
        migrations.AddField(
            model_name='activity',
            name='supervised',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': 'supervised'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activities.category', verbose_name='Supervised for safety'),
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': 'time'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time+', to='activities.category'),
        ),
    ]
