# Generated by Django 3.2.11 on 2022-01-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20210623_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
