# Generated by Django 3.2.12 on 2022-02-17 13:33

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_auto_20220216_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='supervised',
        ),
        migrations.AlterField(
            model_name='activity',
            name='age',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='activities.Age'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='astro_category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='activities.Category', verbose_name='Astronomical Scientific Categories'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='learning',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Enquiry-based learning model', to='activities.Learning', verbose_name='type of learning activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='level',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Specify at least one of "Age" and "Level". ', to='activities.Level', verbose_name='Education level'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='skills',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='activities.Skills', verbose_name='core skills'),
        ),
    ]
