# Generated by Django 3.2.12 on 2022-02-17 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_auto_20220217_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='supervised',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.supervised', verbose_name='Supervised for safety'),
        ),
    ]
