# Generated by Django 3.2.12 on 2022-02-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('activities', '0011_activity_supervised'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fullname', models.CharField(blank=True, help_text='If set, the full name will be used in some places instead of the name', max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='original_author',
            field=models.CharField(blank=True, help_text='Original Author of the activity (if not the authors listed above', max_length=255, null=True),
        ),
        migrations.RenameModel(
            old_name='AuthorInstitution',
            new_name='AuthorInstitute',
        ),
        migrations.AlterField(
            model_name='authorinstitute',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.institute'),
        ),
        migrations.AlterField(
            model_name='person',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.institute'),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
