# Generated by Django 3.2.12 on 2022-02-22 15:13

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_auto_20220222_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorinstitute',
            options={'verbose_name': 'author'},
        ),
        migrations.AddField(
            model_name='activity',
            name='attachments',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(form_classname='title')), ('file', wagtail.documents.blocks.DocumentChooserBlock())], blank=True),
        ),
        migrations.AddField(
            model_name='authorinstitute',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='authorinstitute',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_institute', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='authorinstitute',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.person'),
        ),
        migrations.AlterField(
            model_name='authorinstitute',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.institute'),
        ),
    ]
