# Generated by Django 3.2.12 on 2022-02-22 16:28

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_alter_activity_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='institution',
        ),
        migrations.AlterField(
            model_name='authorinstitute',
            name='activity',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_institute', to='activities.activity'),
        ),
    ]
