# Generated by Django 3.2.12 on 2022-02-22 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_auto_20220222_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.institute'),
        ),
    ]
