# Generated by Django 3.2.12 on 2022-02-25 13:30

from django.db import migrations, models
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_collectionindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='featured',
            field=models.BooleanField(default=False, help_text='Feature on homepage'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='activities',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='collections', to='activities.Activity'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='brief description'),
        ),
    ]
