# Generated by Django 3.2.12 on 2022-02-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_auto_20220225_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='activities',
        ),
        migrations.AddField(
            model_name='collection',
            name='activities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activities.activity'),
        ),
    ]
