# Generated by Django 3.2.12 on 2022-02-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_rename_attachments_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
