# Generated by Django 3.2.12 on 2022-02-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('activities', '0027_auto_20220225_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Main image for listing pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
