# Generated by Django 3.2.12 on 2022-03-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0028_activity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
