# Generated by Django 3.2.12 on 2022-03-03 13:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('activities', '0029_auto_20220303_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='theme',
            field=models.CharField(default='NA', help_text='Use top level AVM metadata', max_length=40),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_items', to='activities.activity')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_keyword_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='keywords',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='activities.Keyword', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
