# Generated by Django 3.2.12 on 2022-03-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0031_alter_activity_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='rtf',
            field=models.FileField(blank=True, help_text='RTF will be autogenerated after publication. Do not upload one.', null=True, upload_to='rtf/'),
        ),
    ]
