# Generated by Django 3.2.12 on 2022-05-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0033_alter_activity_conclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='theme',
            field=models.CharField(blank=True, help_text='Use top level AVM metadata', max_length=40),
        ),
    ]
