# Generated by Django 3.2.12 on 2022-07-21 10:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('activities', '0037_auto_20220711_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Scientific Category', 'verbose_name_plural': 'Scientific Categories'},
        ),
        migrations.AlterModelOptions(
            name='learning',
            options={'verbose_name': 'Area of Learning', 'verbose_name_plural': 'Areas of Learning'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Educational Level'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='supervised',
            options={'verbose_name': 'Supervision', 'verbose_name_plural': 'Supervision'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'Duration', 'verbose_name_plural': 'Duration'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='astro_category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='activities.Category', verbose_name='Old Scientific Categories'),
        ),
        migrations.CreateModel(
            name='SciCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
            ],
            options={
                'verbose_name': 'New Scientific Category',
                'verbose_name_plural': 'New Scientific Categories',
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='activities.SciCategory', verbose_name='New Scientific Categories'),
        ),
    ]
