# Generated by Django 3.2.12 on 2022-08-05 05:24

import activities.models
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0038_auto_20220721_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='age',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='authorinstitute',
            options={'ordering': ['author'], 'verbose_name': 'author'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Scientific Category', 'verbose_name_plural': 'Scientific Categories'},
        ),
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='learning',
            options={'ordering': ['name'], 'verbose_name': 'Area of Learning', 'verbose_name_plural': 'Areas of Learning'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['name'], 'verbose_name': 'Educational Level'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='scicategory',
            options={'ordering': ['name'], 'verbose_name': 'New Scientific Category', 'verbose_name_plural': 'New Scientific Categories'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['name'], 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['name'], 'verbose_name': 'Duration', 'verbose_name_plural': 'Duration'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='age',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, limit_choices_to=activities.models.limit_lang_choice, to='activities.Age'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='astro_category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, limit_choices_to=activities.models.limit_lang_choice, to='activities.Category', verbose_name='Old Scientific Categories'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, limit_choices_to=activities.models.limit_lang_choice, to='activities.SciCategory', verbose_name='New Scientific Categories'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost',
            field=models.ForeignKey(blank=True, limit_choices_to=activities.models.limit_lang_choice, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.cost', verbose_name='Cost per student'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(blank=True, limit_choices_to=activities.models.limit_lang_choice, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.group', verbose_name='Group or individual activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='learning',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Enquiry-based learning model', limit_choices_to=activities.models.limit_lang_choice, to='activities.Learning', verbose_name='type of learning activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='level',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Specify at least one of "Age" and "Level". ', limit_choices_to=activities.models.limit_lang_choice, to='activities.Level', verbose_name='Education level'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(blank=True, limit_choices_to=activities.models.limit_lang_choice, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.location'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='skills',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, limit_choices_to=activities.models.limit_lang_choice, to='activities.Skills', verbose_name='core skills'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='supervised',
            field=models.ForeignKey(blank=True, limit_choices_to=activities.models.limit_lang_choice, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.supervised', verbose_name='Supervised for safety'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.ForeignKey(blank=True, limit_choices_to=activities.models.limit_lang_choice, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.time'),
        ),
    ]
