# Generated by Django 3.2.15 on 2022-09-08 09:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0039_auto_20220805_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='age',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='activities.Age'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='astro_category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='activities.Category', verbose_name='Old Scientific Categories'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='activities.SciCategory', verbose_name='New Scientific Categories'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.cost', verbose_name='Cost per student'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.group', verbose_name='Group or individual activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='learning',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Enquiry-based learning model', to='activities.Learning', verbose_name='type of learning activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='level',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Specify at least one of "Age" and "Level". ', to='activities.Level', verbose_name='Education level'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.location'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='skills',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='activities.Skills', verbose_name='core skills'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='supervised',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.supervised', verbose_name='Supervised for safety'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.time'),
        ),
    ]
