# Generated by Django 3.2.15 on 2022-09-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0040_auto_20220908_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='age',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='authorinstitute',
            options={'ordering': ['sort_order', 'author'], 'verbose_name': 'author'},
        ),
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['order'], 'verbose_name': 'Duration', 'verbose_name_plural': 'Duration'},
        ),
        migrations.AddField(
            model_name='age',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cost',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
