# Generated by Django 3.2.15 on 2022-11-03 14:03

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0041_auto_20220929_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='curriculum',
            field=wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock()), ('htmltext', wagtail.blocks.RawHTMLBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='home/partials/table_template.html'))], blank=True, help_text='Please indicate which country', null=True, use_json_field=None, verbose_name='Connection to school curriculum'),
        ),
    ]
