# Generated by Django 3.2.17 on 2023-02-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0045_person_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='country',
        ),
    ]
