# Generated by Django 3.2.17 on 2023-02-03 15:06

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0046_remove_organization_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
