# Generated by Django 3.2.17 on 2023-02-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0048_organization_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='institution',
        ),
    ]
