# Generated by Django 3.2.17 on 2023-02-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0049_remove_person_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.CharField(help_text='URL slug for this page e.g. my-organization', max_length=255),
        ),
    ]
