# Generated by Django 3.2.17 on 2023-02-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('activities', '0050_alter_organization_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('slug', 'locale'), ('translation_key', 'locale')},
        ),
    ]
