# Generated by Django 3.2.17 on 2023-02-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0051_alter_organization_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institute',
        ),
    ]
