# Generated by Django 3.2.17 on 2023-02-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0054_auto_20230208_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
    ]
