# Generated by Django 3.2.18 on 2023-04-29 15:26

from django.db import migrations, models
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0056_activityindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='additional_information',
            field=wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock()), ('htmltext', wagtail.blocks.RawHTMLBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='activities/partials/table_template.html'))], blank=True, help_text='Notes, Tips, Resources, Follow-up, Questions, Safety Requirements, Variations', use_json_field=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='background',
            field=wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock()), ('htmltext', wagtail.blocks.RawHTMLBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='activities/partials/table_template.html'))], use_json_field=None, verbose_name='Background Information'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='curriculum',
            field=wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock()), ('htmltext', wagtail.blocks.RawHTMLBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='activities/partials/table_template.html'))], blank=True, help_text='Please indicate which country', null=True, use_json_field=None, verbose_name='Connection to school curriculum'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='evaluation',
            field=wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock()), ('htmltext', wagtail.blocks.RawHTMLBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='activities/partials/table_template.html'))], help_text='If the teacher/educator wants to evaluate the impact of the activity, how can she/he do it?', use_json_field=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='fulldesc',
            field=wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock()), ('htmltext', wagtail.blocks.RawHTMLBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='activities/partials/table_template.html'))], use_json_field=None, verbose_name='Full description of the activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='materials',
            field=wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock()), ('htmltext', wagtail.blocks.RawHTMLBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='activities/partials/table_template.html'))], blank=True, help_text='Please indicate costs and/or suppliers if possible', use_json_field=None, verbose_name='List of material'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
