# Generated by Django 3.2.22 on 2023-10-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0058_alter_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='orgs',
            field=models.ManyToManyField(blank=True, null=True, related_name='people', to='activities.Organization'),
        ),
    ]
