# Generated by Django 3.2.22 on 2023-12-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0061_remove_old_org_20231011_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='orgs',
            field=models.ManyToManyField(blank=True, null=True, related_name='organizations', to='activities.Organization'),
        ),
    ]
