# Generated by Django 4.1 on 2024-03-02 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0063_alter_activity_options_alter_keyword_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_type', to='activities.activitytype'),
        ),
    ]
