# Generated by Django 4.1 on 2024-04-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0064_activity_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='astro_category',
        ),
    ]
