# Generated by Django 4.1 on 2024-05-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0065_remove_activity_astro_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='citable_name',
            field=models.CharField(max_length=255),
        ),
    ]
