# Generated by Django 4.1 on 2024-07-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0066_alter_person_citable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='citable_name',
            field=models.CharField(help_text='Name as it should appear in citations, i.e. Surname, Initial', max_length=255),
        ),
    ]
