# Generated by Django 4.1 on 2024-07-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0067_alter_person_citable_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='organization',
            name='partner_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Contributing'), (2, 'Disseminating'), (3, 'Occasional'), (4, 'Other')], default=3),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='translation_key',
        ),
    ]
