# Generated by Django 4.2 on 2025-05-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0068_alter_organization_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityHome',
        ),
    ]
