# Generated by Django 4.2 on 2025-07-13 09:28

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0069_delete_activityhome'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='translator',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='If the activity has been translated, please indicate the translator(s) here. If not, leave blank.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='acknowledgement',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='orgs',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='activities.organization'),
        ),
    ]
