# Generated by Django 5.2.15 on 2026-09-05 15:28

import django.db.models.deletion
import modelcluster.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0071_alter_activitytype_locale_alter_age_locale_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiversitySubTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField()),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Diversity Subtag',
                'verbose_name_plural': 'Diversity Subtags',
                'ordering': ['order'],
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='diversitysub',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='This should related to the Diversity Tag selected', to='activities.diversitysubtag', verbose_name='diversity sub-tag'),
        ),
        migrations.CreateModel(
            name='DiversityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField()),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Diversity Tag',
                'verbose_name_plural': 'Diversity Tags',
                'ordering': ['order'],
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='diversity',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='activities.diversitytag', verbose_name='diversity tag'),
        ),
    ]
