# Generated by Django 5.2.15 on 2026-06-19 10:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230429_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='notice',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='optional notice'),
        ),
    ]
